---
- fail: msg="The host must be part of the kafka group"
  when: "'kafka' not in group_names"

- name: Add the kafka group
  group: name={{ kafka_group }} system=yes

- name: Add the kafka user
  user: name={{ kafka_user }} group={{ kafka_group }} shell=/sbin/nologin system=yes

- name: Create kafka log directories
  file:
    path: "{{ item }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: directory
    recurse: yes
  with_items: "{{ kafka_log_dirs }}"

- name: Download Kafka
  get_url:
    url: "{{kafka_mirror}}/kafka/{{kafka_version}}/kafka_2.11-{{kafka_version}}.tgz"
    dest: /tmp/kafka_2.11-{{kafka_version}}.tgz

- set_fact:
    kafka_broker_id: "{{ groups.kafka.index(inventory_hostname) }}"

- name: Extract download
  unarchive: src=/tmp/kafka_2.11-{{ kafka_version }}.tgz dest=/opt remote_src=yes

- name: Create symbolic link to current installation
  file: src=/opt/kafka_2.11-{{ kafka_version }} path=/opt/kafka state=link

- name: Copy kafka configuration
  template: src=server.properties.j2 dest=/opt/kafka/config/server.properties
  notify:
    - restart kafka

- name: Copy kafka service unit file
  template: src=kafka.service.j2 dest=/etc/systemd/system/kafka.service
  notify:
    - reload systemd
    - restart kafka

- name: Add Kafka to users environment path
  copy: content="export PATH=/opt/kafka/bin:$PATH" dest=/etc/profile.d/kafka.sh

- name: Start Kafka service
  systemd: name=kafka.service state=started enabled=True
